### ISSUE TITLE
Cannot read properties of null (reading 'buttons')

### ISSUE THREAD

**Issue by lisandi** [ether/ep_button_link#9]
After installing the plugin the following 2 error messages appeared - after deinstallation etherpad working again.
![Screen Shot 2021-09-23 at 20 40 24](https://user-images.githubusercontent.com/1982011/134518133-344511d4-5bb0-42b2-989e-c1a9cd0d5912.png)

TypeError: Cannot read properties of null (reading 'buttons')
at unknown at line -1
ErrorId: Loi9wk51ZPZhnEr7mXOa
Unhandled Promise rejection

and

TypeError: Uncaught TypeError: Cannot read properties of undefined (reading 'length')
at https://my.domain/pad/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=57f33620 at line 37
ErrorId: Yv15r6o97Am8OJ4id2HX
Uncaught exception

**Comment by JohnMcLear** [comment]
I imagine the settings.json blob is required but will look into it.

**Comment by JohnMcLear** [comment]
Should be resolved now.
